project_id = "vzmdaszpvfxvqevkhrvd"

[functions.socratic-tutor]
verify_jwt = true

[functions.analytics]
verify_jwt = true

[functions.join-course]
verify_jwt = true

[functions.materials]
verify_jwt = true

[functions.materials-upload]
verify_jwt = true

[functions.materials-text]
verify_jwt = true